// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieList.Areas.ContactList.Models;

namespace MovieList.Migrations.Contact
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieList.Areas.ContactList.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "1234 1st St, West Des Moines, IA 50265",
                            Name = "Mom",
                            PhoneNumber = "515-555-1010"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "123 Tiger Lane, Neighborhood, IA 50001",
                            Name = "Daniel Tiger",
                            Note = "Lizzy's favorite TV Show",
                            PhoneNumber = "515-555-1111"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "123 Treehouse Lane, Neighborhood, IA 50001",
                            Name = "Katerina KittyKat",
                            Note = "My favorite Character",
                            PhoneNumber = "515-555-1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
