// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieList.Models;

namespace MovieList.Migrations.Student
{
    [DbContext(typeof(StudentContext))]
    [Migration("20200619204431_InitialStudentMigration")]
    partial class InitialStudentMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieList.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Hillary",
                            Grade = "A",
                            LastName = "Murphy"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Mary",
                            Grade = "C",
                            LastName = "Allen"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Amanda",
                            Grade = "B",
                            LastName = "Clare"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "William",
                            Grade = "C",
                            LastName = "Bob"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "John",
                            Grade = "B",
                            LastName = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
